# title and introductory test
title: "BRAVE - Bulk RNASeq Analysis and Visualization Engine"
subtitle: "Brave is a end-to-end RNASeq analysis pipeline and integrates qc, alignment, post-alignment metrics, differential expression analysis and results aggregation"
intro_text: "The BRAVE report summarizes results from tools like Fastp, STAR, Picard, Samtools & FeatureCounts"

# report time and analysis paths
show_analysis_paths: False
show_analysis_time: True

# report logo
custom_logo: "logo.png"

# Specify the modules to run
run_modules:
  - fastp
  - star
  - picard
  - samtools
  - featureCounts

module_order:
  - fastp
  - star
  - picard
  - samtools
  - featureCounts

# Specifiy file patterns to recognise
sp:
  fastp:
    fn: "*.json"

  star:
    fn: "*Log.final.out"
  star/genecounts:
    fn: "*ReadsPerGene.out.tab"

  picard/alignment_metrics:
    fn: "*alignment_summary_metrics.txt"

  picard/gcbias:
    fn: "*gcbias.metrics.summary.txt"

  picard/insertsize:
    fn: "*insert_size_metrics.txt"

  picard/markdups:
    fn: "*MarkDuplicates.metrics.txt"

  picard/rnaseqmetrics:
    fn: "*rna_metrics"

  samtools/stats:
    fn: "*Aligned.sortedByCoord.out.bam_stats.txt"

  featureCounts:
    fn: "*.summary"
