$schema: "http://json-schema.org/draft-06/schema#"
description: snakemake configuration file
type: object
properties:
  pipeline:
    description: paths/resource/sample config for the brave pipeline run
    properties:
      benchmarks_dir:
        type: string
        description: path to generate the step benchmarks
      fastq_ext:
        type: string
        description: extension of the input fastq files
      log_dir:
        type: string
        description: path to generate the step logs
      pipeline_input:
        type: string
        description: input directory containing the fastq files
      results:
        type: string
        description: path to generate the pipeline results
      sample_groups:
        description: group of control and condition samples from the samplesheet
        properties:
          condition:
            type: array
          control:
            type: array
      sample_type:
        type: string
        description: type of sequencing library - paired-end/single-end reads
      sample_fastq:
        description: input fastq files for the brave pipeline
        properties:
          condition:
            type: array
          control:
            type: array
      thread:
        type: integer
        description: no. of threads to run the brave pipeline with
      work_dir:
        type: string
        description: working directory for the snakemake workflow manager
  qc:
    description: config for the qc snakefile
    properties:
      output_dir:
        description: output directory for the files generated by the qc snakefile
        type: string
  alignment:
    description: config for the alignment snakefile
    properties:
      input_dir:
        description: input directory for the alignment snakefile (output of qc step)
        type: string
      output_dir:
        description: output directory for the files generated by the alignment snakefile
        type: string
  metrics:
    description: config for the metrics snakefile
    properties:
      input_dir:
        description: input directory for the metrics snakefile (output of alignment step)
        type: string
      output_dir:
        description: output directory for the files generated by the metrics snakefile
        type: string
  counts:
    description: config for the counts snakefile
    properties:
      input_dir:
        description: input directory for the counts snakefile (output of alignment step)
        type: string
      output_dir:
        description: output directory for the files generated by the counts snakefile
        type: string
  aggregate:
    description: config for the aggregate snakefile
    properties:
      output_dir:
        description: output directory for the files generated by the aggregate snakefile
        type: string

required:
  - pipeline
  - qc
  - alignment
  - metrics
  - counts
  - aggregate
